### ISSUE TITLE
[Issue Chat]

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [CHEF-KOCH/NoScript-Whitelist#1]
hey. so is this just a whitelist of domains to allow scripts on? how do you want me to contribute?

**Comment by berrythesoftwarecodeprogrammar** [comment]
also i remember you mentioning noscripts https options. do you force https with noscript? thats what i use my ocsp list for https://github.com/pyllyukko/user.js/issues/73#issuecomment-154274082

**Comment by CHEF-KOCH** [comment]
Hey, sorry I don't really have a 'final goal' yet because I need to hear what the people really need + to discuss what is really necessary/useful. Maybe we can collect together some 'goal', maybe an database for e.g. whitelist or trusted stuff. 

Maybe you can pump your script/list in a format which could be imported/add in NoScript/uMatrix/uBlock or give additional infos how people could handle it.
